"""add phone number

Revision ID: 02598dfd8a68
Revises: 2a1a99420c12
Create Date: 2023-11-14 16:56:19.069197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02598dfd8a68'
down_revision: Union[str, None] = '2a1a99420c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_numner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_numner')
    # ### end Alembic commands ###
