name: Build and Deploy Code

on: [push, pull_request]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run tests
              run: |
                  python -m pytest
            - name: Build and Deploy
              run: |
                  echo "Building and Deploying"
                  echo "Deployed Successfully"
                  echo "Have a great day! :) Hopefully nothing is broken :))"