name: Build and Deploy Code

on: [push, pull_request]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Success Message
              run: |
                  echo "Have a great day! :) Hopefully nothing is broken :))"